#[derive(Debug)]
pub enum PosEventId {
    SUCCESS,
    POS_TRACE_STARTED,
    POS_TRACE_INIT_FAIL,
    UPDATE_ABR_DEBUG_MSG,
    POS_TRACE_ARRAY_CREATED,
    UBIO_WITHOUT_UBLOCKDEV,

    CREATE_ARRAY_NAME_TOO_SHORT = 2503,
    CREATE_ARRAY_NAME_TOO_LONG = 2504,
    CREATE_ARRAY_NAME_INCLUDES_SPECIAL_CHAR = 2505,
    CREATE_ARRAY_NAME_START_OR_END_WITH_SPACE = 2506,

    CREATE_ARRAY_NOT_SUPPORTED_RAIDTYPE = 2509,
    CREATE_ARRAY_RAID_DOES_NOT_SUPPORT_SPARE_DEV = 2511,
}